### ISSUE TITLE
Keep a lifetime running total of space saved

### ISSUE THREAD

**Issue by se1exin** [se1exin/Cleanarr#11]
Originally requested in #10 (`Keep a lifetime running total of space saved (either per server and or per library)`), this issue has been created to split the work out into it's own item due it's potential additional complexity.

**Comment by d8ahazard** [comment]
@se1exin - Just poking through the code, am I correct in understanding that you're currently not using any kind of data storage?

I'd suggest using Python's configparser to create and utilize a single stored config file between the back and frontends. Then you can add configurations for the server IP and port, and add simple storage for the other requested variables, like the total space saved here and the other request to add a "whitelist" of media titles to ignore. ;)

**Comment by se1exin** [comment]
@d8ahazard yep you are correct. The original idea was for it to be stateless and as simple as possible. I think we can add-on the option for some stateful storage - but it should always be optional, and continue to work without it if the user so desires.

That's interesting re: using configparser to store config. I wasn't aware configparser could store data outside of the lifecycle of the application? E.g. if I delete a bunch of movies and then stop the docker container, when I restart the container I would expect the total space saved to be retained. Is stateful storage possible with configparser?

**Comment by d8ahazard** [comment]
> @d8ahazard yep you are correct. The original idea was for it to be stateless and as simple as possible. I think we can add-on the option for some stateful storage - but it should always be optional, and continue to work without it if the user so desires.
> 
> That's interesting re: using configparser to store config. I wasn't aware configparser could store data outside of the lifecycle of the application? E.g. if I delete a bunch of movies and then stop the docker container, when I restart the container I would expect the total space saved to be retained. Is stateful storage possible with configparser?

Yep. More or less, at least. Basically, you load the config with configparser as usual, and then literally just write back to the file with an updated config object as needed. As long as you're not doing a massive amount of async I/O on the file, it's a generally safe practive.

https://stackoverflow.com/questions/6528938/configparser-reading-and-writing

**Comment by d8ahazard** [comment]
Oh, and then for "not requiring it", you basically do the same thing. Anything we're saving/loading, just define a default value first. 

Then, if the user does something to update one of those values, we then save it to a file. You then just do a check for the file on startup, and overwrite the defaults with values from config if they exist. ;)

**Comment by se1exin** [comment]
Added in https://github.com/se1exin/Cleanarr/tree/v2.0.0

Please ensure you docker volume mount a directory to `/config` to ensure that the new database persists across docker restarts
