### ISSUE TITLE
 Failed to load content! - name 'PoolManager' is not defined

### ISSUE THREAD

**Issue by jrcalvert** [se1exin/Cleanarr#123]
Since yesterday I am just getting the below error straight away and no library items returned

Failed to load content!
name 'PoolManager' is not defined

**Comment by opswhisperer** [comment]
same here

**Comment by rukness** [comment]
Getting the same error here.

**Comment by mikekuzak** [comment]
+1

**Comment by peter-mcconnell** [comment]
sorry about that - should be fixed in the latest

**Comment by jrcalvert** [comment]
Thank you. Will try in a few days when I'm back home

**Comment by jrcalvert** [comment]
Thank-you, this is resolved for me now.
