### ISSUE TITLE
Add ability to ignore certain media items

### ISSUE THREAD

**Issue by wogam** [se1exin/Cleanarr#19]
Hi, I love this tool. I was hoping if it would be possible to ignore certain files/episodes/movies. For example, I have two versions of each game of thrones episodes (one from the 1080p Blu-ray and another from the 4k Blu-Ray versions) and would like to keep both (to prevent 4k transcoding). The same with the movie tangled. This causes the queue to be filled up (as it is limited to 50 items), so I can't reduce additional items (plus skimming the same items every time can be draining).

**Comment by se1exin** [comment]
Very similar to #47. Will be implemented as part of #52
