### ISSUE TITLE
Call it "Cleanarr"!

### ISSUE THREAD

**Issue by d8ahazard** [se1exin/Cleanarr#30]
That's it. Not really an issue, but just a thought. It'd fit perfectly, and I think more people than just myself would find it funny as hell. ;)

Either way - great work, I'm gonna give this a go now. :D

**Comment by Alphacosmos** [comment]
bump

**Comment by se1exin** [comment]
Haha I love it! I only worry that if I name it in-line with the bigger players in the OSS home media game (the 'arr' family) I don't have the capacity to keep up with the demand for (the admittedly few) feature requests from the community. E.g. There's already a few feature requests and issues, but I've been a pretty busy with life stuff for the last few months so unfortunately I haven't had the time to action any of them.

Anyway, I love the name suggestion! I'm going to change it accordingly when I get a minute to create a new dockerhub project and update the buildscripts etc.

**Comment by d8ahazard** [comment]
> Haha I love it! I only worry that if I name it in-line with the bigger players in the OSS home media game (the 'arr' family) I don't have the capacity to keep up with the demand for (the admittedly few) feature requests from the community. E.g. There's already a few feature requests and issues, but I've been a pretty busy with life stuff for the last few months so unfortunately I haven't had the time to action any of them.
> 
> Anyway, I love the name suggestion! I'm going to change it accordingly when I get a minute to create a new dockerhub project and update the buildscripts etc.

Awesome! Can't wait! :D

As far as implementing requests - I'm currently also a bit tied up with some other projects, but once those are completed, I'd be happy to lend my knowledge of Plex and Python to this project to help where I can.

**Comment by Alphacosmos** [comment]
D8ahazard aint you the guy that was making Flex.tv? 
Also great app. im making a templete atm for the unraid CA store. If you want to make a official one ill gladly take it down :)

**Comment by d8ahazard** [comment]
Yes sir, that's me. Unfortunately, some API changes mean the app doesn't
currently work. Rewriting the whole thing in c# is another item on my list.
Currently finishing a project called "Glimmr", and then I'll probably start
working on Flex TV again. ;)

**Comment by se1exin** [comment]
@d8ahazard It's done, the project is now named 'Cleanarr'. Thank's for the great name 😄 

The new docker project can be found here: https://hub.docker.com/r/selexin/cleanarr

I've also ensured that the old `plex-library-cleaner` repo continues to receive updates for users that don't see this update message

**Comment by Jerrk** [comment]
i personally dont agree with the rename, i don't really wanna be a gatekeeper for the "arr" family but this repo seems to specifically only work with plex (which isn't even a part of the "arr" family) and doesn't integrate at all with sonarr/radarr/etc.

If that is a plan for the future then i am of course hopeful 🙂
