### ISSUE TITLE
Add support for TV shows

### ISSUE THREAD

**Issue by se1exin** [se1exin/Cleanarr#36]
As per #34 - Only Movies libraries are supported at the moment. Support for TV shows should be added as well.

**Comment by rbleattler** [comment]
WOW! I didn't realize this was only for movies... I actually was over here beating my head against the wall wondering why I can't get it to work for TV Shows 🤦🏻‍♂️

I second this request! 

P.S. @se1exin I'd be happy to help build this functionality out if you lack the bandwidth, just shoot me a message!

**Comment by se1exin** [comment]
@rbleattler hey mate thanks for the offer! I'm pretty swamped with work at the moment, so if you are willing a PR for Movies will be very much welcomed!

**Comment by se1exin** [comment]
Closing: TV support was added in https://github.com/se1exin/Cleanarr/commit/d97cb1eb1b3ed42782dd6d85a28180b6a7db76e3
