### ISSUE TITLE
Ignore Specific File/False Positive

### ISSUE THREAD

**Issue by acharmedmatrix** [se1exin/Cleanarr#47]
Great tool, but I've run into and issue where I have 50 false positives so the queue is jammed. Need to be able to mark as ignored or false positive otherwise I am now trapped at this part of the library.

**Comment by Ahsome** [comment]
@acharmedmatrix I've made some preliminary commits that have added this functionally. Give me a few days and I will upload all the code (it's already working currently, just some visual bugs)

**Comment by se1exin** [comment]
@Ahsome Thanks heaps for working on this! Yep the app has been stateless so-far, but I knew at some point some stateful storage would be required. Please proceed with adding SQLite :)

**Comment by se1exin** [comment]
Functionality to ignore content is now available in `v2.1.0`
