### ISSUE TITLE
V.2.0.0 - No such file or directory /config.db.json

### ISSUE THREAD

**Issue by bolagnaise** [se1exin/Cleanarr#53]
V.2.0.0 seems to have a bug. The below error appears on the latest build, if i switch back to v1.3.0 then no error appears and it works fine. I’m using docker on Unraid.
![671D0828-F979-44E0-A9EA-EE126DA27C89](https://user-images.githubusercontent.com/6158616/166104433-aae1d824-62b6-48db-a8c8-bb9edbd0406d.jpeg)

**Comment by Jerrk** [comment]
I had the same issue, the "/frontend" container path needs to be changed to "/config"

that fixed it for me

**Comment by bolagnaise** [comment]
> I had the same issue, the "/frontend" container path needs to be changed to "/config"
> 
> that fixed it for me

Thanks, that fixed it for me as well.
