### ISSUE TITLE
Error after most recent update

### ISSUE THREAD

**Issue by Frooodle** [se1exin/Cleanarr#54]
After pulling most recent update and adding /config directory i am getting
{"error":"local variable 'episode' referenced before assignment"}
When accessing /content/dupes endpoint

causing
![image](https://user-images.githubusercontent.com/77850077/166127018-d13b018c-da28-4ed6-abb0-ac2e901ba9db.png)

my plex seems to be fine and this only stopped after cleanarr update so assume related

**Comment by se1exin** [comment]
@Frooodle thanks for reporting the issue. Fixed in v2.0.1.
