### ISSUE TITLE
Failed to load content! HTTPConnectionPool(host='192.168.X.X', port=32400): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by vsixtyfour** [se1exin/Cleanarr#60]
Hi,
I'm running the docker on Unraid and im getting the following error:

"Failed to load content!
HTTPConnectionPool(host='192.168.X.XXX', port=32400): Read timed out. (read timeout=30)"

The logs state:
192.168.x.x - - [05/Jun/2022:17:27:31 +1000] "GET /server/deleted-sizes HTTP/1.1" 200 13 "http://192.168.x.y:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36" "-"
[pid: 16|app: 0|req: 1/4] 192.168.x.x () {44 vars in 2747 bytes} [Sun Jun  5 17:27:30 2022] GET /content/dupes => generated 100 bytes in 48158 msecs (HTTP/1.1 500) 3 headers in 123 bytes (1 switches on core 0)
192.168.x.x - - [05/Jun/2022:17:28:19 +1000] "GET /content/dupes HTTP/1.1" 500 100 "http://192.168.x.y:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36" "-"

It might be an issue with library size as i have 1000+ movies?

**Comment by se1exin** [comment]
Hi @vsixtyfour, thanks for reporting the issue.

Looks like Cleanarr is timing out when trying to retrieve media from your plex server.

First thing to try is make sure you are on the latest version (there have been some updates to how media loading is handled recently), and add the following docker environment variable:

```
PAGE_SIZE=25
```

`PAGE_SIZE` determines how many individual media items to load from plex at once. The default value is `50`, but that may be too high for your server. Can you please try a value of `25` and let me know if that helps?

**Comment by pranksta02** [comment]
Hi @se1exin I am getting the same regardless of PAGE_SIZE value on my larger libraries, smaller libraries load up fine. from what I can gather Cleanarr dynamically begins to query plex on opening of the web browser and if it takes longer than 60 seconds to get all the duplicates it seems to time out. Would it be possible to start displaying duplicates as cleanarr finds them, or every ~30s or so to avoid this timeout or alternatively an option for it to run in the background instead of on demand?

**Comment by Zandrox** [comment]
Running into the same issue for a little while now. Unfortunately page size is not solving it for me either.

**Comment by Zandrox** [comment]
My workaround was splitting the movie folder into subfolders with no more than 420 items (seems to be near the limit)

**Comment by vsixtyfour** [comment]
While I appreciate that’s a work around wouldn’t it make more sense to just
batch the files at 400 at a time in the app to avoid the issue altogether?

**Comment by pugslyyy** [comment]
I'm experiencing the same issue recently, again with large libraries.

Is there a way to simply extend the read timeout?
