### ISSUE TITLE
Failed to load content! - Error

### ISSUE THREAD

**Issue by gmoran1016** [se1exin/Cleanarr#61]
I'm running Cleanarr on unraid and it worked when I first set it up but after deleting a few files and restarting it now errors out with 
"Failed to load content!
local variable 'movie' referenced before assignment"

Logs show "main         2022-06-12 20:34:23,514 ERROR    main.py:internal_error local variable 'movie' referenced before assignment"

Thanks!

**Comment by pranksta02** [comment]
Also getting this if I try to only reference a TV Show library in LIBRARY_NAMES variable, if I have a library with movies in it I dont seem to get the error

**Comment by se1exin** [comment]
Thanks for report @gmoran1016 and @pranksta02.

This has been fixed in docker tags `v2.1.3` and `latest`
