### ISSUE TITLE
Fail to scan a TV series Library

### ISSUE THREAD

**Issue by lylmiksistemas** [se1exin/Cleanarr#62]
If i remove this library works good, with several libraries, but if i add the "Series TV" library give me this error, is the last library 

Failed to load content!
Please check your Plex settings and try again.

The library has 3673 TV Series and 47717 Episodes

my docker compose file is 

 cleanarr:
    image: selexin/cleanarr
    container_name: cleanarr
    hostname: cleanarr
    ports:
      - "5000:80"
    environment:
      - BYPASS_SSL_VERIFY=1
      - PLEX_TOKEN=_Z7ioEDxcV8kkcTccmhs
      - PLEX_BASE_URL=http://10.0.3.2:32400
      - LIBRARY_NAMES=Conciertos;Animación TV;Anime TV;Cortos Animación;Documentales TV;Películas;Películas 4K;Películas Anime;Películas Documentales;Series 4K;Series ES;Series TV
    volumes:
      - /root/cleanarr:/config
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /root/sonarr:/config
      - /srv/mergerfs/FractalMerger/MergeLimpio:/Media #optional

Thanks for the help

**Comment by se1exin** [comment]
Hi @lylmiksistemas 

This may be due to your libraries having unicode characters in the name such as `ó`. Can you please try renaming the libraries to use non-unicode characters such `o` instead?

**Comment by lylmiksistemas** [comment]
Hello the name is "Series TV" there is not unicode character in library, I have another library "Animación TV" with ó, and works good.

**Comment by lylmiksistemas** [comment]
I have test with only this library and fail again.
