### ISSUE TITLE
Failed to load content!  [Errno 2] No such file or directory: '/config/db.json'

### ISSUE THREAD

**Issue by Speedmod88** [se1exin/Cleanarr#63]
Hi, 

I installed your docker in Unraid using the lastest version

and I got this when I open the GUI

Failed to load content!
[Errno 2] No such file or directory: '/config/db.json'

the /config folder are empty... (in Unraid -> Appdata/plex-library-cleaner/

need some help please :)
Thank You

**Comment by blackteddybear** [comment]
I have the exact same issue

**Comment by ThomasDK81** [comment]
The config dir is missing.
 
Fix:
Enter the console for this docker and type: mkdir /config
