### ISSUE TITLE
Failed to load content! HTTPConnectionPool(host='144.22.X.X', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60835c7910>: Failed to establish a new connection: [Errno 113] No route to host'))

### ISSUE THREAD

**Issue by mxziino** [se1exin/Cleanarr#79]
How can i solve this error

Failed to load content!
HTTPConnectionPool(host='144.22.X.X', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60835c7910>: Failed to establish a new connection: [Errno 113] No route to host'))

**Comment by peter-mcconnell** [comment]
No route to host means that cleanarr is unable to connect to your plex server - possibly an issue with the address. One way to debug is to connect to the container (e.g. docker compose exec -ti cleanarr bash) and try curl'ing the address

**Comment by peter-mcconnell** [comment]
closing as this thread is quite old. happy to reopen if required
