### ISSUE TITLE
Looking for maintainer(s) for Cleanarr

### ISSUE THREAD

**Issue by se1exin** [se1exin/Cleanarr#99]
As I no longer have the time needed to maintain this project, and I no longer use Plex, I am looking for a maintainer to take over this project.

Please respond to this issue if you are interesting in maintaining this project.

**Comment by peter-mcconnell** [comment]
I can pick it up :+1:

**Comment by se1exin** [comment]
🎉 Wonderful! Thank you! I've just shot you an invite as a collaborator
